"use client"

import { ChevronDown } from "lucide-react"
import { CustomModal } from "@/components/custom/CustomModal"
import type { PriorAuthBillingCode, PriorAuthLinkedEvent } from "@/lib/types/prior-authorization.types"
import { cn } from "@/lib/utils"

// ─── Mock linked events ───────────────────────────────────────────────────────
// TODO (backend): Replace with real API call:
//   GET /client/prior-authorizations/:paId/billing-codes/:codeId/events
// This data is auto-generated by the scheduling/billing engine — read-only.

function getMockLinkedEvents(billingCodeLabel: string): PriorAuthLinkedEvent[] {
  const codeShort = billingCodeLabel
  return [
    {
      id: "evt-1",
      date: "12/10/2025",
      type: "APPOINTMENT",
      time: "2:00 pm – 7:00 pm",
      location: "Home (12)",
      hours: 5,
      units: 20,
      clientName: "Aaliyah Rios",
      userName: "Kiara Furgel",
      billingCodeLabel: `${codeShort} (20)`,
      priorAuthNumber: "11277869",
      status: "COMPLETED",
    },
    {
      id: "evt-2",
      date: "12/11/2025",
      type: "APPOINTMENT",
      time: "2:00 pm – 7:00 pm",
      location: "Home (12)",
      hours: 5,
      units: 20,
      clientName: "Aaliyah Rios",
      userName: "Kiara Furgel",
      billingCodeLabel: `${codeShort} (20)`,
      priorAuthNumber: "11277869",
      status: "COMPLETED",
    },
    {
      id: "evt-3",
      date: "12/12/2025",
      type: "APPOINTMENT",
      time: "1:30 pm – 5:30 pm",
      location: "Home (12)",
      hours: 4,
      units: 16,
      clientName: "Aaliyah Rios",
      userName: "Kiara Furgel",
      billingCodeLabel: `${codeShort} (16)`,
      priorAuthNumber: "11277869",
      status: "COMPLETED",
    },
  ]
}

interface LinkedEventsModalProps {
  open: boolean
  onClose: () => void
  billingCode: PriorAuthBillingCode | null
  paNumber: string
}

export function LinkedEventsModal({
  open,
  onClose,
  billingCode,
  paNumber,
}: LinkedEventsModalProps) {
  if (!billingCode) return null

  const events = getMockLinkedEvents(billingCode.billingCodeLabel)

  return (
    <CustomModal
      open={open}
      onOpenChange={(o) => { if (!o) onClose() }}
      title={`Authorization | ${billingCode.billingCodeLabel}`}
      maxWidthClassName="sm:max-w-[1000px]"
    >
      <div className="px-6 py-5">
        {/* Tabs (read-only — only "Linked events" tab is functional) */}
        <div className="flex gap-1 border-b border-slate-200 mb-5">
          <button
            type="button"
            className="px-4 py-2.5 text-sm font-medium text-slate-500 rounded-t-lg hover:text-slate-700 hover:bg-slate-50 transition-colors"
          >
            General
          </button>
          <button
            type="button"
            className="px-4 py-2.5 text-sm font-medium text-[#037ECC] border-b-2 border-[#037ECC] bg-[#037ECC]/5 rounded-t-lg transition-colors"
          >
            Linked events
          </button>
        </div>

        {/* Events table */}
        <div className="rounded-xl border border-slate-200 overflow-hidden">
          {/* Header */}
          <div className="grid grid-cols-[90px_90px_130px_80px_50px_50px_120px_120px_100px_100px_90px_50px] gap-2 px-3 py-2.5 bg-slate-50 border-b border-slate-200 overflow-x-auto">
            {[
              "Date", "Type", "Time", "Location",
              "Hours", "Units", "Client", "User",
              "Billing codes", "Prior Auth.", "Status", "",
            ].map((h) => (
              <span key={h} className="text-xs font-semibold text-slate-500 uppercase tracking-wider whitespace-nowrap flex items-center gap-1">
                {h}
                {["Date", "Client", "User", "Billing codes", "Status"].includes(h) && (
                  <ChevronDown className="w-3 h-3 text-slate-400" />
                )}
              </span>
            ))}
          </div>

          {/* Rows */}
          <div className="overflow-x-auto max-h-[400px] overflow-y-auto">
            {events.map((evt, idx) => (
              <div
                key={evt.id}
                className={cn(
                  "grid grid-cols-[90px_90px_130px_80px_50px_50px_120px_120px_100px_100px_90px_50px] gap-2 px-3 py-3 items-center",
                  idx < events.length - 1 && "border-b border-slate-100"
                )}
              >
                <span className="text-xs text-slate-700 whitespace-nowrap">{evt.date}</span>
                <span className="text-xs text-slate-600 truncate">{evt.type}</span>
                <span className="text-xs text-slate-600 whitespace-nowrap">{evt.time}</span>
                <span className="text-xs text-slate-600 whitespace-nowrap">{evt.location}</span>
                <span className="text-xs tabular-nums text-slate-700">{evt.hours}</span>
                <span className="text-xs tabular-nums text-slate-700">{evt.units}</span>
                <span className="text-xs text-slate-700 truncate">{evt.clientName}</span>
                <span className="text-xs text-slate-700 truncate">{evt.userName}</span>
                <span className="text-xs text-[#037ECC] font-medium truncate">{evt.billingCodeLabel}</span>
                <span className="text-xs text-slate-700">{evt.priorAuthNumber}</span>
                <span className={cn(
                  "inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-semibold whitespace-nowrap",
                  evt.status === "COMPLETED"
                    ? "bg-emerald-50 text-emerald-700 border border-emerald-200"
                    : "bg-slate-100 text-slate-600 border border-slate-200"
                )}>
                  {evt.status}
                </span>
                <button
                  type="button"
                  className="h-7 w-7 flex items-center justify-center rounded-lg bg-slate-50 border border-slate-200 hover:bg-slate-100 transition-colors"
                  title="View details"
                >
                  <span className="text-[10px] font-bold text-slate-500">⋮⋮</span>
                </button>
              </div>
            ))}
          </div>
        </div>

        <div className="flex justify-end mt-5">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 text-sm font-medium text-slate-600 hover:text-slate-800 transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </CustomModal>
  )
}
